name: kongsi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  auto_route: ^11.1.0
  dio: ^5.10.0
  drift: ^2.34.2
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  json_annotation: ^4.12.0
  path_provider: ^2.1.6
  retrofit: ^4.9.2
  talker_dio_logger: ^5.1.19
  talker_flutter: ^5.1.19
  uuid: ^4.5.3

dev_dependencies:
  auto_route_generator: ^10.6.0
  build_runner: ^2.15.1
  drift_dev: ^2.34.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.14.0
  retrofit_generator: ^10.2.7
  very_good_analysis: ^10.3.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Geist
      fonts:
        - asset: assets/fonts/Geist-Regular.ttf
          weight: 400
        - asset: assets/fonts/Geist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Geist-SemiBold.ttf
          weight: 600